jvdd/argminmax

Cargo.toml
README.md
benches/bench_i8.rs
benches/bench_u8.rs
benches/results
src/lib.rs
src/scalar/generic.rs
src/simd/config.rs
src/simd/generic.rs
src/simd/mod.rs
src/simd/simd_f16.rs
src/simd/simd_i8.rs
src/simd/simd_u16.rs
src/simd/simd_u32.rs
src/simd/simd_u64.rs
src/simd/simd_u8.rs
src/utils.rs

:sparkles: add support for `int8`
-> algorithm: https://stackoverflow.com/a/9798369
:thinking: add support for `uint8`?  
-> would probably require the XOR conversion ~~but would exit the overflow loop 2x fewer than `int8` (guess this will be net 1.5x faster than `int8` for longer arrays)~~ :sweat_smile: nvm still limited by the `i8::MAX` for overflow
TODO: bench + horizontal SIMD implementation for neon
:snowflake: minor improvements
Other stuff

:sparkles: support int8 and uint8

---

.github/workflows/codspeed.yaml
Cargo.toml
benches/bench_f16.rs
benches/bench_f32.rs
benches/bench_f64.rs
benches/bench_i16.rs
benches/bench_i32.rs
benches/bench_i64.rs
benches/bench_i8.rs
benches/bench_u16.rs
benches/bench_u32.rs
benches/bench_u64.rs
benches/bench_u8.rs

To make codspeed work I had to add "half" as default feature. I will revert this once https://github.com/CodSpeedHQ/codspeed-rust/issues/1 is resolved

:rabbit: add codspeed benchmarking to ci/cd

---

benches/bench_f16.rs
benches/bench_f32.rs
benches/bench_f64.rs
benches/bench_i16.rs
benches/bench_i32.rs
benches/bench_i64.rs
benches/bench_i8.rs
benches/bench_u16.rs
benches/bench_u32.rs
benches/bench_u64.rs
benches/bench_u8.rs
src/lib.rs
src/simd/generic.rs
src/simd/mod.rs
src/simd/simd_f16_ignore_nans.rs
src/simd/simd_f32_ignore_nans.rs
src/simd/simd_f32_return_nans.rs
src/simd/simd_f64_ignore_nans.rs
src/simd/simd_i16.rs
src/simd/simd_i32.rs
src/simd/simd_i64.rs
src/simd/simd_i8.rs
src/simd/simd_u16.rs
src/simd/simd_u32.rs
src/simd/simd_u64.rs
src/simd/simd_u8.rs

I'll document the changes tomorrow - a bit too tired now :upside_down_face: 
Long story short -> used more traits & structs to provide more flexibility (& less duplicate code) yay! :tada: 
-- did not add support for aarch64/arm (as I currently do not have access to my ARM testing device)

:recycle: major refactoring

---

Cargo.toml
src/lib.rs
src/scalar/scalar_f16.rs
src/simd/mod.rs
src/simd/simd_f16_ignore_nan.rs
src/simd/simd_f16_return_nan.rs
src/simd/simd_f32_ignore_nan.rs
src/simd/simd_f32_return_nan.rs
src/simd/simd_f64_ignore_nan.rs
src/simd/simd_f64_return_nan.rs
src/simd/simd_i16.rs
src/simd/simd_i32.rs
src/simd/simd_i64.rs
src/simd/simd_i8.rs
src/simd/simd_u16.rs
src/simd/simd_u32.rs
src/simd/simd_u64.rs
src/simd/simd_u8.rs
src/simd/test_utils.rs
tests/argminmax_test.rs

Closes #30, should in general "remove" a lot of duplicate unit test code :)
Decided to keep the tests in each file as this seems the best practice in Rust - see [quote from the book](https://doc.rust-lang.org/book/ch11-03-test-organization.html#unit-tests)
> You’ll put unit tests in the _src_ directory in each file with the code that they’re testing. The convention is to create a module named tests in each file to contain the test functions and to annotate the module with `cfg(test)`.
However, I placed the tests at the bottom of each file (which should significantly enhance the code readability) + limited duplication of tests through using parameterization & centralized generic code (in `test_utils.rs`).
Long story short, this PR should improve the maintainability & flexibility of the …

:recycle: parameterize tests

---

src/simd/test_utils.rs

Fixes a bug in `test_utils.rs` on arm devices in the overflow test.
Left shift value should be clipped at 31 to avoid overflow when performing left-shift on arm - as `usize` on arm is 32-bits.
Note that this case actually never occurs (as we pass `1 << 25` when dealing with `f32` values, but the clipping is necessary to compile the `.unwrap_or`)

fix(test): clip shift size to 31 bits on arm

---

benches/bench_f16_return_nan.rs
benches/bench_f32_ignore_nan.rs
benches/bench_f32_return_nan.rs
benches/bench_f64_ignore_nan.rs
benches/bench_f64_return_nan.rs
src/dtype_strategy.rs
src/lib.rs
src/scalar/generic.rs
src/scalar/mod.rs
src/scalar/scalar_f16.rs
src/simd/config.rs
src/simd/generic.rs
src/simd/mod.rs
src/simd/simd_f16_ignore_nan.rs
src/simd/simd_f16_return_nan.rs
src/simd/simd_f32_ignore_nan.rs
src/simd/simd_f32_return_nan.rs
src/simd/simd_f64_ignore_nan.rs
src/simd/simd_f64_return_nan.rs
src/simd/simd_i16.rs
src/simd/simd_i32.rs
src/simd/simd_i64.rs
src/simd/simd_i8.rs
src/simd/simd_u16.rs
src/simd/simd_u32.rs
src/simd/simd_u64.rs
src/simd/simd_u8.rs
src/simd/task.rs

Make the architecture more flexible;
- less duplicate code
- more clear how traits + structs interoperate
To achieve the type-state pattern is applied for the 
- SIMD structs in `simd/config.rs`
- SCALAR struct in `scalar/generic.rs`

refactor: architecture - use type-state pattern

---

src/scalar/generic.rs
src/simd/simd_f16_return_nan.rs
src/simd/simd_f32_ignore_nan.rs
src/simd/simd_f32_return_nan.rs
src/simd/simd_f64_ignore_nan.rs
src/simd/simd_f64_return_nan.rs
src/simd/simd_i16.rs
src/simd/simd_i32.rs
src/simd/simd_i64.rs
src/simd/simd_i8.rs
src/simd/simd_u16.rs
src/simd/simd_u32.rs
src/simd/simd_u64.rs
src/simd/simd_u8.rs
src/simd/test_utils.rs

Refactors how the shared test code (in `test_utils.rs`) is called.
Previously we passed the functions to this test method, but since #35 it is more clean to pass the structs that implement `SIMDArgMinMax` or `ScalarArgMinMax` 
-> this allows more flexible updates to the tests (e.g, when supporting a new method)

refactor(test): pass struct to tests instead of method

---

.github/workflows/codspeed.yaml
Cargo.toml
benches/bench_f16_return_nan.rs
src/scalar/generic.rs
src/scalar/mod.rs
src/scalar/scalar_f16.rs
src/simd/generic.rs
src/simd/mod.rs
src/simd/simd_f16_ignore_nan.rs
src/simd/simd_f16_return_nan.rs

Since https://github.com/CodSpeedHQ/codspeed-rust/issues/1 is solved we can remove `"half"` from the default-features :tada: 
Changes contributed in this PR:
- make `"half"` feature non-default
- upgrade `codspeed-criterion-compat` to 1.1
- remove unnecessary `#[cfg(feature = "half")]`

ci: upgrade codspeed & make half non-default feature

---

.github/workflows/ci.yml
Cargo.toml
src/lib.rs
src/scalar/generic.rs
src/scalar/scalar_f16.rs
src/simd/generic.rs
src/simd/mod.rs
tests/argminmax_test.rs

Resolves #22 
* Add a new feature (which is default) named "float" for (`f32` and `f64`)
* Extend tests in CI to for different features

feat: add new default float feature

---

src/scalar/generic.rs
src/simd/test_utils.rs

Fixes a bug in `SCALAR<FloatIgnoreNaN>` when the first element in the array is NaN.
The code used an else-if for updating low / max - but this should be 2 seperate ifs to allow double update when the first non-NaN value is encountered.

fix: allow double update in scalar ignore nan implementation

---

src/scalar/generic.rs

perf: tune scalar argmin & argmax

---

benches/bench_f16_return_nan.rs
src/scalar/generic.rs
src/scalar/scalar_f16.rs

feat:  optimize + add `f16` scalar implementations

---

src/lib.rs

The return type of `PrimitiveArray.values()` is changed to `&ScalarBuffer` in arrow v36 - https://github.com/apache/arrow-rs/pull/3896
-> to comply with this (and retrieve the slice) we should call [`.as_ref()`](https://docs.rs/arrow-buffer/36.0.0/arrow_buffer/buffer/struct.ScalarBuffer.html#method.as_ref) now after the `.values()`

chore: comply with breaking api change in arrow `v36`

---

Cargo.toml
README.md
src/lib.rs
tests/argminmax_test.rs

:tada: add optional arrow2 support

---

.github/workflows/ci.yml
Cargo.toml
src/lib.rs
src/simd/config.rs
src/simd/generic.rs
src/simd/mod.rs
src/simd/simd_f16_ignore_nan.rs
src/simd/simd_f16_return_nan.rs
src/simd/simd_f32_ignore_nan.rs
src/simd/simd_f32_return_nan.rs
src/simd/simd_f64_ignore_nan.rs
src/simd/simd_f64_return_nan.rs
src/simd/simd_i16.rs
src/simd/simd_i32.rs
src/simd/simd_i64.rs
src/simd/simd_i8.rs
src/simd/simd_u16.rs
src/simd/simd_u32.rs
src/simd/simd_u64.rs
src/simd/simd_u8.rs

- for `x86` / `x86_64`: this results in not allowing AVX512
- for `arm` / `aarch64`: currently no NEON features will be supported

feat: add "nightly_simd" feature to allow stable build

---

benches/bench_f64_ignore_nan.rs
benches/bench_f64_return_nan.rs
benches/bench_i64.rs
benches/bench_u64.rs
src/lib.rs
src/simd/generic.rs
src/simd/mod.rs
src/simd/simd_f16_ignore_nan.rs
src/simd/simd_f16_return_nan.rs
src/simd/simd_f32_ignore_nan.rs
src/simd/simd_f32_return_nan.rs
src/simd/simd_f64_ignore_nan.rs
src/simd/simd_f64_return_nan.rs
src/simd/simd_i16.rs
src/simd/simd_i32.rs
src/simd/simd_i64.rs
src/simd/simd_i8.rs
src/simd/simd_u16.rs
src/simd/simd_u32.rs
src/simd/simd_u64.rs
src/simd/simd_u8.rs

Closes #51 
- Add SIMD implementations + trigger tests
Other TODO's
---
Also a big thanks to @matdemeue for lending me a rpi4, allowing to tune & validate the `aarch64` code

feat: add 64-bit aarch64 SIMD implementation

---

src/simd/simd_u16.rs
src/simd/simd_u32.rs
src/simd/simd_u64.rs
src/simd/simd_u8.rs

Enhances the performance for `arm` / `aarch64` uint operations by using uint as `MAX_INDEX` instead of int.
This results in 2x fewer exits from the inner SIMD loop (and thus 2x less - much slower - horizontal SIMD ops) :tada: 
main branch :arrow_down:
```txt
scalar_u8_argminmax     time:   [274.45 µs 274.47 µs 274.48 µs]
scalar_u8_argmin        time:   [274.52 µs 274.53 µs 274.54 µs]
scalar_u8_argmax        time:   [274.51 µs 274.52 µs 274.54 µs]
neon_u8_argminmax       time:   [58.060 µs 58.072 µs 58.089 µs]
neon_u8_argmin          time:   [38.840 µs 38.843 µs 38.846 µs]
neon_u8_argmax          time:   [38.836 µs 38.837 µs 38.840 µs]
impl_u8_argminmax       time:   [58.059 µs 58.062 µs 58.065 µs]
impl_u8_argmin          time:   [38.869 µs 38.870 µs 38.871 µs]
impl_u8_argmax …
```

perf: use uint `MAX_INDEX` on `arm` / `aarch64` for uint SIMD

---

benches/bench_f16_ignore_nan.rs
benches/bench_f16_return_nan.rs
benches/bench_f32_ignore_nan.rs
benches/bench_f32_return_nan.rs
benches/bench_f64_ignore_nan.rs
benches/bench_f64_return_nan.rs
benches/bench_i16.rs
benches/bench_i32.rs
benches/bench_i64.rs
benches/bench_i8.rs
benches/bench_u16.rs
benches/bench_u32.rs
benches/bench_u64.rs
benches/bench_u8.rs
src/lib.rs

fix: remove `stdsimd` feature; add `stdarch_x86_avx512`

---

Cargo.toml
src/lib.rs
src/simd/generic.rs
src/simd/simd_f16_ignore_nan.rs
src/simd/simd_f16_return_nan.rs
src/simd/simd_f32_ignore_nan.rs
src/simd/simd_f32_return_nan.rs
src/simd/simd_f64_ignore_nan.rs
src/simd/simd_f64_return_nan.rs
src/simd/simd_i16.rs
src/simd/simd_i32.rs
src/simd/simd_i64.rs
src/simd/simd_i8.rs
src/simd/simd_u16.rs
src/simd/simd_u32.rs
src/simd/simd_u64.rs
src/simd/simd_u8.rs

:hourglass_flowing_sand: I'll work further on this once I get my hands on a rpi4 (because checking my code oon AArch64 with github ci-cd is not that convenient :upside_down_face: :upside_down_face:)

enh: remove `simd_nightly` feature flag for `aarch64`

---

.github/workflows/codspeed.yaml
Cargo.toml
src/simd/mod.rs

:see_no_evil: add full copy of half to dev dep with rand_distr feature
